//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Newspaper.Properties
{
    using System.IO;
    using System.Windows.Media;
    using System.Windows.Media.Imaging;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Newspaper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type BitmapImage.
        /// </summary>
        internal static BitmapImage MainWindow_Icon
        {
            get
            {
                BitmapImage image = new();
                object obj = ResourceManager.GetObject("MainWindow_Icon", resourceCulture);

                image.BeginInit();
                image.StreamSource = new MemoryStream((byte[])obj);
                image.EndInit();

                return image;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type FontFamily.
        /// </summary>
        internal static FontFamily FontFamily => new FontFamily("Monotype Corsiva");

        /// <summary>
        ///   Looks up a localized resource of type double.
        /// </summary>
        internal static double FontSize => 16.0;

        /// <summary>
        ///   Looks up a localized string similar to Newspaper.
        /// </summary>
        internal static string MainWindow_Title => "Newspaper";

        /// <summary>
        ///   Looks up a localized resource of type SolidColorBrush.
        /// </summary>
        internal static SolidColorBrush Primary => new(Color.FromRgb(255, 255, 255));

        /// <summary>
        ///   Looks up a localized resource of type SolidColorBrush.
        /// </summary>
        internal static SolidColorBrush Secondary => new(Color.FromRgb(198, 215, 255));

        /// <summary>
        ///   Looks up a localized resource of type SolidColorBrush.
        /// </summary>
        internal static SolidColorBrush Accent => new(Color.FromRgb(70, 178, 157));

        /// <summary>
        ///   Looks up a localized resource of type SolidColorBrush.
        /// </summary>
        internal static SolidColorBrush Black => new(Color.FromRgb(0, 0, 0));

        /// <summary>
        ///   Looks up a localized resource of type SolidColorBrush.
        /// </summary>
        internal static SolidColorBrush Transparent => new(Color.FromArgb(0, 0, 0, 0));
    }
}
